# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('salary', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('role', models.ManyToManyField(to='app01.Role')),
            ],
            options={
                'verbose_name_plural': '类型表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('tp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Type')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
